// source: protobuf/ava/avs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.aggregator.TaskAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.aggregator.ContractExecution');
goog.require('proto.aggregator.ETHTransfer');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aggregator.TaskAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aggregator.TaskAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aggregator.TaskAction.displayName = 'proto.aggregator.TaskAction';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aggregator.TaskAction.prototype.toObject = function(opt_includeInstance) {
  return proto.aggregator.TaskAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aggregator.TaskAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aggregator.TaskAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    ethTransfer: (f = msg.getEthTransfer()) && proto.aggregator.ETHTransfer.toObject(includeInstance, f),
    contractExecution: (f = msg.getContractExecution()) && proto.aggregator.ContractExecution.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aggregator.TaskAction}
 */
proto.aggregator.TaskAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aggregator.TaskAction;
  return proto.aggregator.TaskAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aggregator.TaskAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aggregator.TaskAction}
 */
proto.aggregator.TaskAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.aggregator.ETHTransfer;
      reader.readMessage(value,proto.aggregator.ETHTransfer.deserializeBinaryFromReader);
      msg.setEthTransfer(value);
      break;
    case 2:
      var value = new proto.aggregator.ContractExecution;
      reader.readMessage(value,proto.aggregator.ContractExecution.deserializeBinaryFromReader);
      msg.setContractExecution(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aggregator.TaskAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aggregator.TaskAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aggregator.TaskAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aggregator.TaskAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEthTransfer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.aggregator.ETHTransfer.serializeBinaryToWriter
    );
  }
  f = message.getContractExecution();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.aggregator.ContractExecution.serializeBinaryToWriter
    );
  }
};


/**
 * optional ETHTransfer eth_transfer = 1;
 * @return {?proto.aggregator.ETHTransfer}
 */
proto.aggregator.TaskAction.prototype.getEthTransfer = function() {
  return /** @type{?proto.aggregator.ETHTransfer} */ (
    jspb.Message.getWrapperField(this, proto.aggregator.ETHTransfer, 1));
};


/**
 * @param {?proto.aggregator.ETHTransfer|undefined} value
 * @return {!proto.aggregator.TaskAction} returns this
*/
proto.aggregator.TaskAction.prototype.setEthTransfer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aggregator.TaskAction} returns this
 */
proto.aggregator.TaskAction.prototype.clearEthTransfer = function() {
  return this.setEthTransfer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aggregator.TaskAction.prototype.hasEthTransfer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ContractExecution contract_execution = 2;
 * @return {?proto.aggregator.ContractExecution}
 */
proto.aggregator.TaskAction.prototype.getContractExecution = function() {
  return /** @type{?proto.aggregator.ContractExecution} */ (
    jspb.Message.getWrapperField(this, proto.aggregator.ContractExecution, 2));
};


/**
 * @param {?proto.aggregator.ContractExecution|undefined} value
 * @return {!proto.aggregator.TaskAction} returns this
*/
proto.aggregator.TaskAction.prototype.setContractExecution = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aggregator.TaskAction} returns this
 */
proto.aggregator.TaskAction.prototype.clearContractExecution = function() {
  return this.setContractExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aggregator.TaskAction.prototype.hasContractExecution = function() {
  return jspb.Message.getField(this, 2) != null;
};


